version: '3'

volumes:
  mysql_data:
      driver: local

services:

  mysql:
      image: mysql:8
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password 
      networks:
        - backend  
   
  keycloak:
      image: quay.io/keycloak/keycloak:20.0.2
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "connectTimeout=30000"
      ports:
        - 8080:8080
      depends_on:
        - mysql
      networks:
        - backend
      command:
        - start-dev
  springboot:
      build: ./../kc-spring-boot
      volumes:
        - /data/springboot-app  
      ports: 
        - 8050:8050
      networks:
        - backend  
  angular-crm:
      build: ./../kc-crm
      ports:
        - 5000:5000
      volumes:
        - /app/kc-crm
      networks:
          - backend      
  angular-sea:
      build: ./../kc-angular
      ports:
        - 4200:4200
      volumes:
        - /app/kc-sea
      networks:
          - backend
networks:
   backend:  
      driver: bridge              